### ISSUE TITLE
depraction of `np.complex`

### ISSUE THREAD

**Issue by maxmargraf** [pycomlink/pycomlink#121]
Importing pycomlink within the [Opensense sandbox](https://github.com/OpenSenseAction/OPENSENSE_sandbox) in a locally built env gives an attribute error due the [deprecation of np.complex](https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations). This seems not to be a problem in the recent test but changing np.complex to complex sounds save to me, hence I would open a PR on this.

**Comment by maxmargraf** [comment]
Here is the associate error message:
![image](https://github.com/pycomlink/pycomlink/assets/44392812/62c03ebb-f02f-422a-9072-d880b6f696d7)

**Comment by maxmargraf** [comment]
The issue could be that pycomlink is pinned to [this version](https://github.com/pycomlink/pycomlink/tree/12fc302539851b19f7656cf7e2438c0ddbaa48bf) in the [OpenSense sandbox](https://github.com/OpenSenseAction/OPENSENSE_sandbox).
Anyway, PR can be checked and merged (and updated in the sandbox)

**Comment by cchwala** [comment]
closed via #122

**Comment by maxmargraf** [comment]
removing another occurance of `np.complex` with #123.
