### ISSUE TITLE
python 3.11 incompatible with pycomlink 0.3.8

### ISSUE THREAD

**Issue by jpolz** [pycomlink/pycomlink#130]
to be done

**Comment by cchwala** [comment]
As you wrote on mattermost this might be cause by pining scipy < 1.9 which I did in https://github.com/pycomlink/pycomlink/pull/104. But the related problems in `pykrige` should be solved https://github.com/GeoStat-Framework/PyKrige/issues/261. Hence, we should just remove this version pinning.

**Comment by cchwala** [comment]
closed via #132
