### ISSUE TITLE
Tensorflow in requirements.txt

### ISSUE THREAD

**Issue by eoydvin** [pycomlink/pycomlink#152]
In #151 tensorflow was removed from the environment files. While reinstalling pycomlink from developer files running `pip install -e pycomlink` I noticed that pip still installs tensorflow. This is due to that setup.py installs all packages listed in `requirements.txt`, which still has tensorflow listed. I will fix this when I add sckikit-learn in soon up and coming PR.

**Comment by cchwala** [comment]
Thanks for pointing out this issue.

Yes, please add this minor fix in your other PR, even though it is not directly within its scope, but related...

**Comment by cchwala** [comment]
Closed in #156
