### ISSUE TITLE
Min-max data processing algorithm bugs

### ISSUE THREAD

**Issue by DanSereb** [pycomlink/pycomlink#43]
Issue for tracking bugs in the min-max data processing algorithm.

First bug found in **pycomlink/processing/processor.py** :
in A_R class, polarization is missing when calling calc_R_from_A_min_max().

The **pol** argument should be added to calc_R_min_max field of A_R class:
self.calc_R_min_max = cml_wrapper(cml, calc_R_from_A_min_max, ..., **pol=cml.channel_1.metadata['polarization']**)

**Comment by DanSereb** [comment]
Bug found in **pycomlink/processing/processor.py** :
In function  _calc_A_min_max(), found an error in calculation of Ac_max/Ac_min:
Ac_max = tx_max - rx_min **+** (gT + gR) / 2
Ac_min = tx_min - rx_max **-** (gT + gR) / 2

The above code should be replaced with (sign changes):
Ac_max = tx_max - rx_min **-** (gT + gR) / 2
Ac_min = tx_min - rx_max **+** (gT + gR) / 2

**Comment by DanSereb** [comment]
Bug found in **pycomlink/processing/processor.py** :
In function _calc_A_min_max(), the bold line should be added to ensure _Ar_max_ is never negative:
    # zero-level calculation
    Ar_max = np.full(Ac_max.shape, np.nan)
    for i in range(window,len(Ac_max)):
        Ar_max[i] = Ac_max[i] - Ac_min[i-window:i+1].min()
    Ar_max[0:window] = np.nan
    **Ar_max[Ar_max<0] = 0.0**

**Comment by cchwala** [comment]
Closed in #45
