### ISSUE TITLE
CI fails because of package version mismatch, probably between numba and numpy

### ISSUE THREAD

**Issue by cchwala** [pycomlink/pycomlink#92]
CI fails because 
```
 RuntimeError: module compiled against API version 0xe but this version of numpy is 0xd
```
during imports within `numba`, see https://github.com/pycomlink/pycomlink/runs/3459934170

This is most likely caused by https://github.com/numba/numba/issues/7339

**Comment by cchwala** [comment]
Pinning to older versions of numba like https://github.com/matchms/ms2deepscore/pull/93 should resolve the issue for now. Not sure how long a general fix from numba will take.

**Comment by maxmargraf** [comment]
numba version from working test:
numba-0.53.1-cp37-cp37m-manylinux2014_x86_64.whl
numba version from failing test:
numba-0.54.0-cp37-cp37m-manylinux2014_x86_64.manylinux_2_17_x86_64.whl

**Comment by cchwala** [comment]
temporarily fixed in #93, but I keep this open so that we unpin numba later when there is an upstream fix for this issue

**Comment by cchwala** [comment]
should work now according to https://github.com/numba/numba/issues/7339

i will unpin numba for the next PR #97

**Comment by cchwala** [comment]
works now. closing via #97
