### ISSUE TITLE
Missing files in conda-forge build

### ISSUE THREAD

**Issue by maxmargraf** [pycomlink/pycomlink#96]
Some files which are present in the github repo are missing in the recent [conda-forge build file](https://anaconda.org/conda-forge/pycomlink/files). 

The missing files I am aware of are:
`pycomlink/processing/wet_dry/cnn_model_files/model_2020.002.180m.h5`
`pycomlink/processing/wet_dry/cnn_model_files/model_2020.002.180m.json`

**Comment by cchwala** [comment]
some example data seem also to be missing as reported by @jpolz 
```
FileNotFoundError: [Errno 2] No such file or directory: b'/home/polz-j/miniconda3/envs/agrain/lib/python3.9/site-packages/pycomlink/io/example_data/example_path_averaged_reference_data.nc'
```
```
pycomlink                 0.3.3              pyhd8ed1ab_0    conda-forge
```

**Comment by maxmargraf** [comment]
Further missing files in the conda build are:
* `pycomlink/io/example_data/example_path_averaged_reference_data.nc`
* `pycomlink/io/example_dataexample_areal_reference_data.nc`
  
e.g.
```
FileNotFoundError: [Errno 2] No such file or directory: b'/Users/graf-m/miniconda3/envs/pycomlink_workshop/lib/python3.9/site-packages/pycomlink/io/example_data/example_path_averaged_reference_data.nc'
```

**Comment by cchwala** [comment]
Looks as if the last conda build was on 12th of August 2021, but the files have been added later in August... Hence, just making a new release should fix the issue with the example files. Do they need an update?

**Comment by maxmargraf** [comment]
`pycomlink/io/example_dataexample_areal_reference_data.nc` is unused at the moment, but would need an update (fixing the spatial extent to the example data) when used in the future.

**Comment by cchwala** [comment]
okay, so not urgent now? spatial extent is more or less okay?
